# Generated by Django 5.2.3 on 2025-06-26 02:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('HIIT', 'HIIT')], max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('total_slots', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_slots', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitness Class',
                'verbose_name_plural': 'Fitness Classes',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='studio.fitnessclass')),
            ],
            options={
                'ordering': ['-booked_at'],
                'unique_together': {('fitness_class', 'client_email')},
            },
        ),
    ]
